name: medhub
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.10+1
  page_transition: ^2.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_screenutil: ^5.9.3
  intro_slider: ^4.2.1
  smooth_page_indicator: ^1.2.0+3
  introduction_screen: ^3.1.14

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logoApp.png"

flutter: 
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Overpass
      fonts:
        - asset: assets/fonts/Overpass-Bold.ttf
        - asset: assets/fonts/Overpass-BoldItalic.ttf
        - asset: assets/fonts/Overpass-Italic.ttf
        - asset: assets/fonts/Overpass-Regular.ttf
        - asset: assets/fonts/Overpass-SemiBold.ttf
        - asset: assets/fonts/Overpass-SemiBoldItalic.ttf
        - asset: assets/fonts/Overpass-Light.ttf
        - asset: assets/fonts/Overpass-Medium.ttf  
  uses-material-design: true

  
